import 'package:flutter/material.dart';
import '../../../../core/theme/app_palette.dart';
import '../../../../domain/entities/customer_activity_entity.dart';

class CustomerPortalScreen extends StatefulWidget {
  const CustomerPortalScreen({super.key});

  @override
  State<CustomerPortalScreen> createState() => _CustomerPortalScreenState();
}

class _CustomerPortalScreenState extends State<CustomerPortalScreen> {
  final List<CustomerActivityEntity> _activities = [
    CustomerActivityEntity(
      id: 'act_01',
      customerId: 'cust_987',
      bookingId: 'bk_2026_101',
      eventType: 'INQUIRY_SUBMITTED',
      description: '12 Sep — Inquiry submitted for Royal Bridal Makeup (20 Nov)',
      timestamp: DateTime.parse('2026-09-12 10:30:00'),
    ),
    CustomerActivityEntity(
      id: 'act_02',
      customerId: 'cust_987',
      bookingId: 'bk_2026_101',
      eventType: 'QUOTE_GENERATED',
      description: '12 Sep — Quote ₹20,500 generated by Prachi',
      timestamp: DateTime.parse('2026-09-12 11:15:00'),
    ),
    CustomerActivityEntity(
      id: 'act_03',
      customerId: 'cust_987',
      bookingId: 'bk_2026_101',
      eventType: 'QUOTE_VIEWED',
      description: '13 Sep — Quote viewed on web portal',
      timestamp: DateTime.parse('2026-09-13 09:00:00'),
    ),
    CustomerActivityEntity(
      id: 'act_04',
      customerId: 'cust_987',
      bookingId: 'bk_2026_101',
      eventType: 'DEPOSIT_RECEIVED',
      description: '13 Sep — ₹5,000 advance deposit paid via Razorpay',
      timestamp: DateTime.parse('2026-09-13 09:12:00'),
    ),
    CustomerActivityEntity(
      id: 'act_05',
      customerId: 'cust_987',
      bookingId: 'bk_2026_101',
      eventType: 'BOOKING_CONFIRMED',
      description: '13 Sep — Booking confirmed & 20 Nov date locked',
      timestamp: DateTime.parse('2026-09-13 09:13:00'),
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppPalette.backgroundDark,
      appBar: AppBar(
        title: const Text(
          'My Bridal Dashboard',
          style: TextStyle(color: AppPalette.textGold, fontWeight: FontWeight.bold),
        ),
        backgroundColor: AppPalette.surfaceDark,
        elevation: 0,
        actions: [
          IconButton(
            icon: const Icon(Icons.link, color: AppPalette.textGold),
            tooltip: 'Link Guest Booking',
            onPressed: _showLinkBookingDialog,
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildUpcomingBookingCard(),
            const SizedBox(height: 20),
            const Text(
              'MY SAVED LOOKS & REFERENCES',
              style: TextStyle(color: AppPalette.textSecondary, fontSize: 11, fontWeight: FontWeight.bold, letterSpacing: 1.2),
            ),
            const SizedBox(height: 12),
            _buildSavedLooksGallery(),
            const SizedBox(height: 24),
            const Text(
              'BOOKING ACTIVITY TIMELINE',
              style: TextStyle(color: AppPalette.textSecondary, fontSize: 11, fontWeight: FontWeight.bold, letterSpacing: 1.2),
            ),
            const SizedBox(height: 12),
            _buildTimelineList(),
          ],
        ),
      ),
    );
  }

  Widget _buildUpcomingBookingCard() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppPalette.surfaceDark,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: AppPalette.goldAccent.withValues(alpha: 0.4)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'UPCOMING BOOKING',
                style: TextStyle(color: AppPalette.textGold, fontSize: 12, fontWeight: FontWeight.bold),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                decoration: BoxDecoration(
                  color: Colors.green.withValues(alpha: 0.2),
                  borderRadius: BorderRadius.circular(4),
                ),
                child: const Text('CONFIRMED 🔒', style: TextStyle(color: Colors.greenAccent, fontSize: 10, fontWeight: FontWeight.bold)),
              ),
            ],
          ),
          const SizedBox(height: 12),
          const Text('Royal Bridal Airbrush Makeup', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),
          const SizedBox(height: 4),
          const Text('📅 20 November 2026 • 📍 Lake Palace Resort, Jodhpur', style: TextStyle(color: AppPalette.textSecondary, fontSize: 13)),
          const Divider(color: Colors.white12, height: 24),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              _buildPriceItem('Total Amount', '₹20,500', AppPalette.textGold),
              _buildPriceItem('Deposit Paid', '₹5,000', Colors.greenAccent),
              _buildPriceItem('Remaining Due', '₹15,500', Colors.amber),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildPriceItem(String label, String val, Color color) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(val, style: TextStyle(color: color, fontSize: 15, fontWeight: FontWeight.bold)),
        const SizedBox(height: 2),
        Text(label, style: const TextStyle(color: AppPalette.textSecondary, fontSize: 10)),
      ],
    );
  }

  Widget _buildSavedLooksGallery() {
    final looks = [
      {'title': 'Rajasthani Royal Bride', 'category': 'Bridal'},
      {'title': 'Pastel Floral Draping', 'category': 'Pre-Wedding'},
      {'title': 'Soft Glam Airbrush', 'category': 'Reception'},
    ];

    return SizedBox(
      height: 100,
      child: ListView.separated(
        scrollDirection: Axis.horizontal,
        itemCount: looks.length,
        separatorBuilder: (context, index) => const SizedBox(width: 10),
        itemBuilder: (context, index) {
          final look = looks[index];
          return Container(
            width: 140,
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: AppPalette.surfaceDark,
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: Colors.white10),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Icon(Icons.bookmark_outline, color: AppPalette.textGold, size: 20),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(look['title']!, style: const TextStyle(color: Colors.white, fontSize: 12, fontWeight: FontWeight.bold), overflow: TextOverflow.ellipsis),
                    Text(look['category']!, style: const TextStyle(color: AppPalette.textSecondary, fontSize: 10)),
                  ],
                ),
              ],
            ),
          );
        },
      ),
    );
  }

  Widget _buildTimelineList() {
    return ListView.separated(
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      itemCount: _activities.length,
      separatorBuilder: (context, index) => const SizedBox(height: 8),
      itemBuilder: (context, index) {
        final act = _activities[index];
        return Container(
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: AppPalette.surfaceDark,
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: Colors.white10),
          ),
          child: Row(
            children: [
              const Icon(Icons.check_circle_outline, color: Colors.greenAccent, size: 16),
              const SizedBox(width: 10),
              Expanded(
                child: Text(act.description, style: const TextStyle(color: Colors.white70, fontSize: 12)),
              ),
            ],
          ),
        );
      },
    );
  }

  void _showLinkBookingDialog() {
    final bookingIdController = TextEditingController();
    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        title: const Text('Link Guest Booking'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              'Enter your booking reference ID to link an existing guest booking to your account portal.',
              style: TextStyle(fontSize: 12),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: bookingIdController,
              decoration: const InputDecoration(labelText: 'Booking ID (e.g. bk_2026_101)'),
            ),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
          ElevatedButton(
            onPressed: () {
              Navigator.pop(context);
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Guest booking linked to account successfully.')),
              );
            },
            child: const Text('Link Booking'),
          ),
        ],
      ),
    );
  }
}
